### ISSUE TITLE
Spinner and autohide "false" is not working with CLI 8.0.0

### ISSUE THREAD

**Issue by desmeit** [apache/cordova-plugin-splashscreen#153]
I added the following to the config:

```
<plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
<preference name="AutoHideSplashScreen" 	   value="false" />
<preference name="SplashScreen" value="screen" />
<preference name="SplashScreenDelay" value="12000" />
<preference name="show-splash-screen-spinner" value="false" />
```

<splash src="res/screen/ios/Default@2x~universal~anyany.png" />

The Splashscreen is working but it is showing the spinner. And the second issue: I added to autohidesplashscreen "false". but the splashscreen is hiding automatically (without setting navigator.splashscreen.hide();)

Please help.

**Comment by janpio** [comment]
Android or iOS?
Did it work for you with older CLI?

**Comment by desmeit** [comment]
On IOS. I cannot test Android because there are many other issues.
With 6.5.0 it was working perfectly.

**Comment by desmeit** [comment]
It would be nice to keep 6.5.0 but there is no way for me to get it to work with Iphone X.
Or do you have a trick to work with 6.50 and Iphone X?

**Comment by desmeit** [comment]
I solved it now with this fork:

https://github.com/desmeit/cordova-plugin-splashscreen.git#985d6a7

But I think this is just a temporary solution.

**Comment by desmeit** [comment]
and 

`<preference name="FadeSplashScreen" value="false"/>`

is also not working. I get a fade on the end. nothing is working with this plugin and CLI 8.0.0.

**Comment by janpio** [comment]
If you have additional problems, open additional issues. Nobody will see it here as the title doesn't mention it.

**Comment by Lefystore** [comment]
Same here, using phonegap build cli-8.0.0 the splash screen hides a second after its shown even if you set AutoHideSplashScreen. SplashScreenDelay not working either

**Comment by breautek** [comment]
Closing because of staleness of the issue. CLI 8 is old and the issue may be no longer relevant with modern versions of cordova-ios / CLI / splashscreen plugin.

Additionally, cordova-plugin-splashscreen is no longer supports iOS as splashscreen code has been moved to the core platform.

If this issue occurs on current versions of iOS, an issue should be raised with updated information in the [cordova-ios](https://github.com/apache/cordova-ios/issues) repository.
