### ISSUE TITLE
Can't set AutoHideSplashScreen to false in IOS (CLI 8.0.0)

### ISSUE THREAD

**Issue by desmeit** [apache/cordova-plugin-splashscreen#154]
I added the following code to the config:

```
<preference name="AutoHideSplashScreen" value="false" />
<preference name="SplashScreen" value="screen" />
<preference name="SplashScreenDelay" value="12000" />
```

and try to hide it with 

`navigator.splashscreen.hide();`

Thats not working. The Splashscreen hides automatically.

I tried also:

```
<feature name="SplashScreen">
    <param name="ios-package" value="CDVSplashScreen"/>
    <param name="onload" value="true" />
</feature>
```

as I read hier: https://stackoverflow.com/questions/17821526/setting-autohidesplashscreen-has-no-effect-in-cordova-3-0-0-for-ios

I cannot believe that such basic features are not working in cordova. Why is Adobe not solving such issues?

**Comment by janpio** [comment]
1. Why did you create a second issue when you already mentioned this problem in https://github.com/apache/cordova-plugin-splashscreen/issues/153? Please update the other one not to mention the problem any more.
2. As you are the only one reporting this, it is highly unprobable that this is generally broken.
3. I think you misread the repo organisation. It is "apache", as in "Apache Software Foundation", not "Adobe".

**Comment by desmeit** [comment]
This is not helping.

**Comment by desmeit** [comment]
Okay, Autohide is solving. But the spinner is already showing although I set it to false.

**Comment by janpio** [comment]
Can you share what the problem was? Future readers might benefit from your solution.

**Comment by desmeit** [comment]
There was one more

`navigator.splashscreen.hide();`

**Comment by leftdead7** [comment]
I am also facing this issue, the splashscreen is hiding in within an second

**Comment by mekemike** [comment]
> on android its fine, But i am having the issue on iOS.

$(document).on('deviceready ', function () {
setTimeout(function() {
navigator.splashscreen.hide();
}, 3000);
});

This works using PGB included on the index file as opposed to config.xml.
