### ISSUE TITLE
Not working for iPhone XR and XS max

### ISSUE THREAD

**Issue by anchalsahu** [apache/cordova-plugin-splashscreen#164]
The splash screen is not showing in XR and XS Max devices.

I have fixed this and since I do not have permission to update this repo I am uploading compressed file here with fixes.

[CDVSplashScreen.zip](https://github.com/apache/cordova-plugin-splashscreen/files/2456031/CDVSplashScreen.zip)

**Comment by janpio** [comment]
Please create a Pull Request on this repository with your changes. Then we can review the code changes and accept them into this code base. Thanks.

**Comment by sdgpalm2** [comment]
See early issue #158, the code for this #159 has been submitted and which is in the Ready for Review state.

**Comment by Manaspaul623** [comment]
> The splash screen is not showing in XR and XS Max devices.
> 
> I have fixed this and since I do not have permission to update this repo I am uploading compressed file here with fixes.
> 
> [CDVSplashScreen.zip](https://github.com/apache/cordova-plugin-splashscreen/files/2456031/CDVSplashScreen.zip)

Not working in cordova 9.0 and ios 5.0
only showing cordova icon splashscreen on iphone x,xs,xs max,xr

**Comment by jcesarmobile** [comment]
The plugin has been integrated into cordova-ios 6, so no more iOS work will be done here.
Also, it now uses the launch storyboards, so this shouldn't be an issue anymore.
If there are still other bugs on the cordova-ios 6 implementation, report them on https://github.com/apache/cordova-ios/issues
