### ISSUE TITLE
Invoke plugin initialize if the os restore the app

### ISSUE THREAD

**Issue by xGeorge** [apache/cordova-plugin-splashscreen#168]
If the OS restore(reset) the app a white screen is showing, unfortunately the cordova init and deviceready it's still not available

**Comment by janpio** [comment]
What platform are you referring to?
What is happening when exactly?

**Comment by xGeorge** [comment]
At the moment android, basically im invoking a sdk(intent) but if it takes more than 5 minutes the OS restores the webview, this is a common behavior by the OS another sceniario is if the device doesnt have enough ram and the app(WV) its on background

**Comment by janpio** [comment]
I still don't know what is happening when.

**Comment by xGeorge** [comment]
webview ..invoke(intent).....-> sdk activity,
OS .....if needs memory.... -> reset o frees memory from background task, activity or apps
sdk activity ...invoke(callback)...-> webview(binded callback)
webview was restored so it will load again the webview
