### ISSUE TITLE
I cannot disable splashscreen

### ISSUE THREAD

**Issue by Nelife** [apache/cordova-plugin-splashscreen#175]
Hi!
I have a problem to hide the splashscreem.
This my config in config.xml
![image](https://user-images.githubusercontent.com/12018657/49950498-8206e780-ff2a-11e8-91dd-ec08fb796fda.png)
Please help me to hide the splashscreen.
Thank you so much!

**Comment by janpio** [comment]
What are the indicators that you are still seeing the splashscreen that can be hidden with this setting?

**Comment by Nelife** [comment]
> What are the indicators that you are still seeing the splashscreen that can be hidden with this setting?

I want hide it!
![img_1763 1](https://user-images.githubusercontent.com/12018657/49954570-5c321080-ff33-11e8-8eb6-1c551e5359a1.PNG)

**Comment by hadassaChemouni** [comment]
@janpio I have the same problem, When I do:
```
    <preference name="SplashScreenDelay"           value="3000" />
    <preference name="AutoHideSplashScreen"        value="false" />
```
The splash screen doesn't hide.
But when I remove `AutoHideSplashScreen` and do:
```
    <preference name="SplashScreenDelay"           value="3000" />
```
The splash screen hide correctly.

**Comment by janpio** [comment]
> <preference name="AutoHideSplashScreen"        value="false" />

This is the preference that defines that the splashscreen does not hide by itself, but has to be hidden explicitly by using the `hide()` method - so this is doing exactly what it should.
