### ISSUE TITLE
Hiding splash screen in android fails

### ISSUE THREAD

**Issue by Steffen911** [apache/cordova-plugin-splashscreen#176]
I added the plugin in version 5.0.2 to my application and on android it regularly fails with:
```
D/SystemWebChromeClient: file:///android_asset/www/build/vendor.js: Line 105224 : Ionic Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.
I/chromium: [INFO:CONSOLE(105224)] "Ionic Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.", source: file:///android_asset/www/build/vendor.js (105224)
D/SystemWebChromeClient: file:///android_asset/www/build/vendor.js: Line 105236 : Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen'
I/chromium: [INFO:CONSOLE(105236)] "Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen'", source: file:///android_asset/www/build/vendor.js (105236)
````
I tried to remove the platforms and plugins directories in my application and tried a prod and a dev build.

I use the following settings in my config.xml:
```
  <preference name="FadeSplashScreenDuration" value="300"/>
  <preference name="SplashScreenDelay" value="10000"/>
  <preference name="ShowSplashScreenSpinner" value="false"/>
  <preference name="SplashMaintainAspectRatio" value="true"/>
  <preference name="AutoHideSplashScreen" value="false"/>
  <preference name="FadeSplashScreen" value="false"/>
  <preference name="ShowSplashScreen" value="true"/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="SplashShowOnlyFirstTime" value="false"/>
  <plugin name="cordova-plugin-splashscreen" spec="^5.0.2"/>
```
and `<engine name="android" spec="7.0.0"/>`.

On iOS it works perfectly fine. Could anyone assist here?

**Comment by Steffen911** [comment]
Apparently this is only reproducible when I set the `android:targetSdkVersion` in my AndroidManifest.xml to version 28 instead of 26.

**Comment by Steffen911** [comment]
New update: This happens for all targetSdkVersions and sometimes also on the iPhone, but less frequently with the newer targetSdkVersion.

**Comment by Steffen911** [comment]
Apparently another method in the code tried to call splashScreen.hide() before the platform.isReady() event was fired. Now it works.

**Comment by tryhardest** [comment]
@Steffen911 could pls elaborate on now it works? Did you make a change for it to do so? Tnx

**Comment by Steffen911** [comment]
@tryhardest Yes, I had multiple calls of splashScreen.hide() in my code and in some cases one fired before the platform.isReady() callback was triggered. I removed all references to splashScreen.hide() and retained only the one in the isReady callback.
