### ISSUE TITLE
APP could not hide the splash screen properly.

### ISSUE THREAD

**Issue by benjamin0809** [apache/cordova-plugin-splashscreen#177]
There is no problem under normal use. When APP enters the background for a period of time (about half a day), it will be stuck in the splash screen when it enters the APP again.

**Comment by janpio** [comment]
What platform are you talking about?
What is your plugin configuration?
Why does it show the splashscreen after being in background?
Did you remote debug your app to see if your app itself crashed?

**Comment by breautek** [comment]
Closing as stale.
