### ISSUE TITLE
Android occur crash by java.lang.NullPointerException

### ISSUE THREAD

**Issue by ihaoqichan** [apache/cordova-plugin-splashscreen#178]
Logcat message:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setAnimation(android.view.animation.Animation)' on a null object reference
at org.apache.cordova.splashscreen.SplashScreen$4.run(SplashScreen.java:230)
at android.app.Activity.runOnUiThread(Activity.java:6216)
at org.apache.cordova.splashscreen.SplashScreen.removeSplashScreen(SplashScreen.java:220)
at org.apache.cordova.splashscreen.SplashScreen.access$1000(SplashScreen.java:50)
at org.apache.cordova.splashscreen.SplashScreen$5$1.run(SplashScreen.java:337)

=======================================================
My config.xml setup <preference name="SplashScreenDelay" value="10000" />,
when my application launched and invoke navigator.splashscreen.hide() in 3 seconds,
if it launch again in 7 seconds, crash occurs.

=======================================================
My solution: add splashImageView != null at org.apache.cordova.splashscreen.SplashScreen.removeSplashScreen(SplashScreen.java:222)

I'm sorry, my english is not so good.

**Comment by cristoj** [comment]
Me too. But not in all devices, in pixel 2 for example.
The version of plugin is 5.0.2

----
Ionic:

   ionic (Ionic CLI)  : 4.9.0 (C:\Users\crist\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\android-sdk)
   NodeJS            : v11.7.0 (D:\programas\node\node.exe)
   npm               : 6.7.0
   OS                : Windows 10

**Comment by cristoj** [comment]
More info:

Tamaño de la pantalla: 1080×1920
Duración de la prueba: 300 segundos
Densidad de pantalla (ppp): 420
Nombre del modelo: Pixel 2
RAM: 4096 MB
Fabricante: Google
Versión de OpenGL ES: 3.2
Versión de Android: Android 9
Plataforma nativa: armeabi-v7a
Configuración regional: es_ES
Marca de CPU: Qualcomm
Modelo de CPU: MSM8998

Problema: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setAnimation(android.view.animation.Animation)' on a null object reference

**Comment by cristoj** [comment]
Fix if remove fade efect:

<preference name="FadeSplashScreen" value="false" />

**Comment by adamulator** [comment]
> Fix if remove fade efect:

Hello,
I'm having similar problem with this plugin. Could you please post your solution again? I don't see anything. Thank you.

**Comment by kobojsaren** [comment]
This issue was solved over one year ago (Jan 25 2018). The same day as the last release (5.0.2) but unfortunately was not included in that release. We would really like to get this in, would it be possible to make a new release?

**Comment by mbunge** [comment]
This would be really, really nice!!!

> This issue was solved over one year ago (Jan 25 2018). The same day as the last release (5.0.2) but unfortunately was not included in that release. We would really like to get this in, would it be possible to make a new release?

**Comment by ihaoqichan** [comment]
I'm sorry about that, my project was created by ionic CLI(v4.8.0+), cordova CLI(v8.1.0+) and Cordova Platform's Android@7.1.1. I didn't notice the Android code for this plugin is different in the two projects. The plugin in this github is perfect. And The plugin for Cordova Platform's Android@7.1.1 is not using this github's version.

**Comment by ihaoqichan** [comment]
> This issue was solved over one year ago (Jan 25 2018). The same day as the last release (5.0.2) but unfortunately was not included in that release. We would really like to get this in, would it be possible to make a new release?

Nice!

**Comment by fdambrosio** [comment]
I have the same problem, app crashes on Android 9.0, using 
"cordova-plugin-splashscreen": "^5.0.2"

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.4
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic 4.0.0, (and 20 other plugins)

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

**Comment by timbru31** [comment]
Is any of you guys interested in creating a PR? ;)  
This would speedup a fix of this issue! 👍

**Comment by timbru31** [comment]
Pardon my first comment, this seems like it's already fixed in the master with the PR https://github.com/apache/cordova-plugin-splashscreen/pull/149/files.
Can you confirm that installing the plugin from git solves this issue?

**Comment by fquirin** [comment]
I'm getting the same error and had the same idea to fix it as in the PR linked above (https://github.com/apache/cordova-plugin-splashscreen/pull/149/files) but with one difference: I think we should remove the second null check to keep these lines:
```
splashDialog.dismiss();
splashDialog = null;
splashImageView = null;
```
... just in case the splashDialog actually exists or not?

Is installing from Git the new standard way now for this plugin?

**Comment by Jonkat323** [comment]
I came across this issue yesterday after installing the APK on a Galaxy S5 with CLI9. App crashes on launch but if I remove the splashscreen plugin then everything works.

**Comment by breautek** [comment]
> I came across this issue yesterday after installing the APK on a Galaxy S5 with CLI9. App crashes on launch but if I remove the splashscreen plugin then everything works.

Ensure that you're using the up-to-date version of splashscreen. Version 5.0.3 has a [PR](https://github.com/apache/cordova-plugin-splashscreen/pull/149/files) that addresses this issue. If this does not work for you, I'd recommend creating a new issue.

This issue should have been closed, but was likely missing the github close keywords, so I'm closing this issue now.

**Comment by chuchuva** [comment]
@breautek I observe crashes in version 5.0.3. I created https://github.com/apache/cordova-plugin-splashscreen/issues/298
