### ISSUE TITLE
Freezes on iOS 9.x

### ISSUE THREAD

**Issue by ppetree** [apache/cordova-plugin-splashscreen#179]
Building on PGB

**Build settings**
```
    <preference name="phonegap-version" value="cli-8.0.0" />
    <preference name="pgb-builder-version" value="2" />
```

**Preferences**
```
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="FadeSplashScreen" value="false" />
```

**Plugin (with version)**
```
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
```

App Starts, splash screen is displayed, spinner starts revolving, statusbar displays... no further processing happens.

If I remove the plugin, the app starts normally.  This is working on iOS 10.x and 11.x (not tested on 12.x).

**Comment by janpio** [comment]
Can you please create a plain Cordova app with this configuration and upload it to a Github repository so we can recreate this?

**Comment by ppetree** [comment]
We're no longer supporting iOS 9.x.
