### ISSUE TITLE
Can't  add cordova-plugin-splashscreen

### ISSUE THREAD

**Issue by petertsu** [apache/cordova-plugin-splashscreen#181]
I am trying to add plugin and fail with the following errors:
cordova plugin add cordova-plugin-splashscreen

Failed to fetch plugin cordova-plugin-splashscreen@5.0.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\petert\AppData\Roaming\npm-cache\_logs\2019-01-31T09_48_20_212Z-debug.log

cordova --version
8.1.2 (cordova-lib@8.1.1)

node --version
v10.15.1

**Comment by janpio** [comment]
That looks like a local problem with your node/npm install. Nothing we can do about that @petertsu, sorry. The fix usually is to mess with the npm cache or reinstall npm/node to get a clean environment.
