### ISSUE TITLE
SplashScreenDelay has no effect...

### ISSUE THREAD

**Issue by cmeuser** [apache/cordova-plugin-splashscreen#183]
The SplashScreenDelay has no affect on Android (Pixel 3 XL).  I have played around with the value with and without the --prod flag with no success.  Launching the app, regardless of the setting value, displays the splash screen for a second (flash) and then disappears.  

    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="4000" />
    <preference name="SplashScreenSpinnerColor" value="white" />

Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/meusercx/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v9.11.1 (/usr/local/bin/node)
   npm               : 6.7.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by yurik94** [comment]
+1

**Comment by janpio** [comment]
> cordova (Cordova CLI) : 8.0.0
> Cordova Platforms : android 7.0.0

Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

**Comment by Cimera42** [comment]
I'm getting the same issue. I did a bit of debugging and found that the `onPause` event is being called on the app on startup, which causes the splashscreen to hide instantly.

**Comment by ediks** [comment]
Similar issue here. Setting AutoHideSplashScreen to false and/or changing the SplashScreenDelay value (3000 or 30000) seems to be ignored somehow. I want to manually hide the splash screen after platformReady() but whatever values and/or combination of true/false I enter in my config.xml, it doesn't seem to register. Only setting the FadeSplashScreen to true/false works, but the splash screen itself keeps disappearing after a few seconds resulting in a temporary white screen... In previous projects (Ionic <3) I never had any issues. Any ideas?

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\ediks\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.0
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (c:\dev\bin\Android\SDK)
   NodeJS            : v8.10.0 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

relevant config.xml preferences:

    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="30000" />
    <preference name="ShowSplashScreenSpinner" value="true" />
    <preference name="SplashScreenSpinnerColor" value="#ffd520" />
    <preference name="FadeSplashScreen" value="false" />
    <preference name="FadeSplashScreenDuration" value="0" />
    <preference name="AutoHideSplashScreen" value="false" />

**Comment by janpio** [comment]
Did you upgrade your Cordova tooling @cmeuser as I suggested?
