### ISSUE TITLE
Spinner is no longer centered on Android 9

### ISSUE THREAD

**Issue by alexhisen** [apache/cordova-plugin-splashscreen#184]
# Bug Report
After upgrading phone to Android 9, splash screen spinner in Cordova app shows at bottom of screen instead of centered vertically

## Problem
Splash screen spinner shows at bottom of screen on Android 9 instead of centered vertically

### What is expected to happen?
Splash screen spinner should show vertically centered

### What does actually happen?
Splash screen spinner shows at the bottom of the screen

### Environment, Platform, Device
Android 9 on Samsung S9+ AT&T One UI 1.0 2220x1080 resolution

config.xml:
```
       <preference name="AutoHideSplashScreen" value="false" />
        <preference name="FadeSplashScreen" value="false" />
        <preference name="SplashMaintainAspectRatio" value="true" />
        <preference name="SplashShowOnlyFirstTime" value="false" />
```
### Version information
cordova-plugin-splashscreen 5.0.2
The app was built with cordova 8.0.0 and cordova-android 5.2.2

## Checklist
- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

![screenshot_20190223-152715_pregnancy coach](https://user-images.githubusercontent.com/19575231/53292939-ea224700-377f-11e9-8bed-64d4c67e0c9c.jpg)

**Comment by janpio** [comment]
A screenshot would be nice here.

**Comment by janpio** [comment]
Thanks @alexhisen, I missed your edit as one does not get any notification from GitHub on these.

Is this the default spinner on that device? Looks a bit different from what I expected.

**Comment by alexhisen** [comment]
Yes. It's a snapshot. When animated, it obviously looks more like a standard Material UI circle spinner.

**Comment by janpio** [comment]
Do you have the time to create a new Cordova app, add the plugin and take a screenshot with that device and post it here? That would help us prioritize this (happens in any Cordova app vs. happens in your specific Cordova app) and save us a bit of time. Thanks.

**Comment by alexhisen** [comment]
I would imagine you already have some kind of sample or test Cordova app that you use. I've updated the task description with my splash screen settings in config.xml and attached are the images themselves that you can try in it. If you send me the apk I can try it on my phone. The image itself is rendered exactly centered as expected.
![XXXHDPI](https://user-images.githubusercontent.com/19575231/57198298-ed774300-6f25-11e9-8e92-06d87cca1541.png)
![HDPI](https://user-images.githubusercontent.com/19575231/57198299-ee0fd980-6f25-11e9-91ce-7a3987e12a81.png)
![MDPI](https://user-images.githubusercontent.com/19575231/57198300-ee0fd980-6f25-11e9-9fb4-d6f648a4deec.png)
![XHDPI](https://user-images.githubusercontent.com/19575231/57198301-ee0fd980-6f25-11e9-8969-cf697e23669a.png)
![XXHDPI](https://user-images.githubusercontent.com/19575231/57198302-ee0fd980-6f25-11e9-844f-2f5eed2060e0.png)

**Comment by janpio** [comment]
No I don't, but `cordova create` gives you one in a minute. Add the plugin and take a screenshot if it reproduces. (You should not have to add any images as the plugin usually falls back to common Cordova image)

**Comment by alexhisen** [comment]
cordova create ...
cordova platform add android@5.2.2
cordova plugin add cordova-plugin-splashscreen
cordova run android --device
![Screenshot_20190505-113438_CordovaTest](https://user-images.githubusercontent.com/19575231/57198649-fc5ff480-6f29-11e9-8aaa-c892fb8e494b.jpg)

**Comment by janpio** [comment]
Awesome, thanks!

**Comment by davidquon** [comment]
This issue is also happening using Ionic Framework on Android 9 using the latest Ionic and Cordova versions.

Here is the info from `$ ionic info`:
```
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.7 (/Users/davidquon/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.802.1
   @angular-devkit/schematics    : 8.2.1
   @angular/cli                  : 8.2.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/davidquon/Library/Android/sdk)
   NodeJS            : v10.16.3 (/Users/davidquon/.nvm/versions/node/v10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
```

**Comment by zabojad** [comment]
Any news here?
