### ISSUE TITLE
Build errors about drawable since upgrading to cordova-android 8.0.0

### ISSUE THREAD

**Issue by BorntraegerMarc** [apache/cordova-plugin-splashscreen#185]
# Bug Report

### What is expected to happen?
Building a cordova app with `ionic cordova build android --prod --release` does not throw errors.

### What does actually happen?
I see this error in the console:
```
/platforms/android/app/src/main/res/drawable-land-hdpi/screen.png: Error: The drawable "screen" in drawable-land-hdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
```

## Information

This error was not present in v7.X

I do specify a splash screen in `config.xml` like so: `<splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />`

And it gets displayed correctly (according to my tests so far)

I'm using this plugin to configure the splash screens: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/

I only included 1 example of the errors I'm getting to keep the bug report small. But I get it for different screen sizes & densities.

I understand that it has something to do with android linting rules: http://tools.android.com/tips/lint-checks

But I don't fully understand if it's a misconfiguration in the plugin or if cordova-android needs to do something differently.

PS: I also posted a bug here https://github.com/apache/cordova-android/issues/689 because I'm not sure where the problem is (if in the plugin or cordova-android).

### Command or Code

`ionic cordova build android --prod --release`

### Environment, Platform, Device

On all. It happens on build time.

### Version information

```
~/Documents/komed/komed-frontend$ ionic info

Ionic:

   ionic (Ionic CLI)  : 4.11.0 (/Users/borntsch/.nvm/versions/node/v8.13.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 8.0.0, browser 5.0.4, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 2.3.1, (and 27 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/borntsch/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v8.13.0 (/Users/borntsch/.nvm/versions/node/v8.13.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by BorntraegerMarc** [comment]
It only happens with a production "release" build.

**Comment by janpio** [comment]
@BorntraegerMarc Can you please post the complete output of one of these builds? Best with a new Cordova app that you just created to reproduce this error, then it will be even simpler for us to understand. Bonus points if it is a plain Cordova app, not using Ionic (because that removes another variable). Thanks.

**Comment by janpio** [comment]
(There is more discussion in the related general cordova-android issue: https://github.com/apache/cordova-android/issues/689)
