### ISSUE TITLE
can not disable the splash screen

### ISSUE THREAD

**Issue by hassan-1993** [apache/cordova-plugin-splashscreen#189]
# Bug Report

## Problem
i am trying to hide and disable the splash screen

### What is expected to happen?
All i want is to remove the splash screen screen from the ionic app 

### What does actually happen?
the splash screen is still showing 

### Command or Code

To disable the splashscreen i added the following preference to config.xml:

> `<preference name="SplashScreenDelay" value="0"/>` but it's not working

**Comment by ChezRD** [comment]
Maybe you should do `cordova rm cordova-plugin-splashscreen` then?

**Comment by mario350cc** [comment]
cordova plugin rm cordova-plugin-splashscreen

**Comment by janpio** [comment]
@hassan-1993 Did you try removing the plugin to fix your problem?

**Comment by mario350cc** [comment]
Yes I have remove the plugin
This was giving problem only in 12.1 version

**Comment by janpio** [comment]
So removing the plugin did disable the splash screen successfully?



>  This was giving problem only in 12.1 version

What does this mean? What problem? Version 12.1 of what?

**Comment by mario350cc** [comment]
Sorry I have commented on wrong page

Removing plugin will remove splash screen
but it still show the loader

Better solution is remove the plugin but still upload splash screen images from xcode

**Comment by janpio** [comment]
That is an iOS thing called ["Launch Screen"](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/) that can not be changed. This plugin is about adding a splash screen shown after the launch screen while your app is loading.

**Comment by breautek** [comment]
Closing as stale.
