### ISSUE TITLE
Android: White screen before splash screen

### ISSUE THREAD

**Issue by hungtranpg** [apache/cordova-plugin-splashscreen#197]
# Bug Report
White screen before splash screen
## Problem
When app opening, it shows the white screen before the splash screen
### What is expected to happen?
The splash screen should have come immediately when app opening

### Command or Code
In `config.xml`:
`<preference name="SplashScreen" value="screen" />`
   `<preference name="FadeSplashScreen" value="false" />`
    `<preference name="ShowSplashScreenSpinner" value="false" />`
    `<preference name="AutoHideSplashScreen" value="false" />`
    `<preference name="SplashMaintainAspectRatio" value="true" />`
    `<preference name="SplashShowOnlyFirstTime" value="false" />`
    `<preference name="SplashScreenDelay" value="0" />`
Run: `cordova run android`

### Environment, Platform, Device
`Node version: v6.9.1`
`Cordova version: 8.1.1`
`cordova-plugin-splashscreen 5.0.2 "Splashscreen"`
` cordova platform: android 6.3.0`
`ionic v1`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Does this happen in a new plain Cordova project created with `cordova create` as well?

**Comment by hungtranpg** [comment]
I'm not sure, but my project was created for a long time ago.
FYI, I just try on new project `cordova create hello com.example.hello HelloWorld` and **Splash Screen is still delayed, a gray screen appears first**

**Comment by janpio** [comment]
What makes the screen white for your app vs. the green one you observed for a new app?

**Comment by IndieSW** [comment]
Have you tried using a splash screen theme?

**Comment by hungtranpg** [comment]
> What makes the screen white for your app vs. the green one you observed for a new app?
The white screen in my app and the gray in the new app same behavior. They appear in about 1s then splash screen appears.

> Have you tried using a splash screen theme?

I'm using splash screen image, it's required :D

`<platform name="android">`
        `<allow-intent href="market:*" />`
        `<splash density="port-ldpi" src="resources\android\splash\drawable-port-ldpi-screen.png" />`
        `<splash density="port-mdpi" src="resources\android\splash\drawable-port-mdpi-screen.png" />`
        `<splash density="port-hdpi" src="resources\android\splash\drawable-port-hdpi-screen.png" />`
        `<splash density="port-xhdpi" src="resources\android\splash\drawable-port-xhdpi-screen.png" />`
        `<splash density="port-xxhdpi" src="resources\android\splash\drawable-port-xxhdpi-screen.png" />`
        `<splash density="port-xxxhdpi" src="resources\android\splash\drawable-port-xxxhdpi-screen.png" />`
    `</platform>`

**Comment by hungtranpg** [comment]
I have resolved this issue by using a new android theme style
1. Create a new style file in path `\platforms\android\res\values\`    `styles.xml`
2. `styles.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
   <style name="Theme.Transparent" parent="android:style/Theme.DeviceDefault.Light.NoActionBar">
      <item name="android:windowDisablePreview">true</item>
  </style>
</resources>
``` 
As I'm using `Theme.DeviceDefault.Light.NoActionBar` in `AndroidManifest.xml`, so I set parent theme as above.

3. Update theme in `AndroidManifest.xml`
`<application .... android:theme="@style/Theme.Transparent"`
4. Done

@janpio Did you able to reproduce it? if possible please review and update your source code to fix it.

**Comment by evromalarkey** [comment]
windowDisablePreview indeed resolve the issue for me, thanks for the tip @hungtranpg

**Comment by simone-compagnone** [comment]
With this solution, I have a problem.
When I install the apk on simulator or device and tap many time on the icon app, the view open with white splashscreen. Do you have the same problem @hungtranpg ?
Thank you

**Comment by hungtranpg** [comment]
Yes, sometimes if tap many times on the icon app. 
But I think the customer will not do that 😄

**Comment by MVDeveloper1** [comment]
> I have resolved this issue by using a new android theme style
> 
> 1. Create a new style file in path `\platforms\android\res\values\`    `styles.xml`
> 2. `styles.xml`
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>    <style name="Theme.Transparent" parent="android:style/Theme.DeviceDefault.Light.NoActionBar">
>       <item name="android:windowDisablePreview">true</item>
>   </style>
> </resources>
> ```
> 
> As I'm using `Theme.DeviceDefault.Light.NoActionBar` in `AndroidManifest.xml`, so I set parent theme as above.
> 
> 1. Update theme in `AndroidManifest.xml`
>    `<application .... android:theme="@style/Theme.Transparent"`
> 2. Done
> 
> @janpio Did you able to reproduce it? if possible please review and update your source code to fix it.



> I have resolved this issue by using a new android theme style
> 
> 1. Create a new style file in path `\platforms\android\res\values\`    `styles.xml`
> 2. `styles.xml`
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>    <style name="Theme.Transparent" parent="android:style/Theme.DeviceDefault.Light.NoActionBar">
>       <item name="android:windowDisablePreview">true</item>
>   </style>
> </resources>
> ```
> 
> As I'm using `Theme.DeviceDefault.Light.NoActionBar` in `AndroidManifest.xml`, so I set parent theme as above.
> 
> 1. Update theme in `AndroidManifest.xml`
>    `<application .... android:theme="@style/Theme.Transparent"`
> 2. Done

IT WORKED LIKE A CHARM! I've been looking for the solution for a long time, but now I have found it. Thanks a lot!

**Comment by dwasyluk** [comment]
Thanks @hungtranpg I can confirm that fix works. I was able to just add `<item name="android:windowDisablePreview">true</item>` to the default `AppTheme` and that did the trick.

**Comment by rozza-m** [comment]
Not sure why this was closed, if you hadn't done this workaround it would still be a problem...the workaround isn't documented, and there's not quite enough info in this thread for others (i.e. me) who experience the same thing to fix.

**Comment by rozza-m** [comment]
For others who experience the same thing - [this](https://stackoverflow.com/questions/30994342/customizing-the-blank-screen-before-splash-screen-and-videos-not-playing-in-full) was the solution for me:

> In the "platforms\android" folder under your project [platforms\android\app\src\main], open the AndroidManifest.xml and search for android:theme inside the <activity> tag that contains android:name="MainActivity" and change the default value (that is android:theme="@android:style/Theme.DeviceDefault.NoActionBar") to android:theme="@android:style/Theme.Translucent". Save the file and build your project again, the grey screen should desapear.

**Comment by msd117** [comment]
> For others who experience the same thing - [this](https://stackoverflow.com/questions/30994342/customizing-the-blank-screen-before-splash-screen-and-videos-not-playing-in-full) was the solution for me:
> 
> > In the "platforms\android" folder under your project [platforms\android\app\src\main], open the AndroidManifest.xml and search for android:theme inside the  tag that contains android:name="MainActivity" and change the default value (that is android:theme="@android:style/Theme.DeviceDefault.NoActionBar") to android:theme="@android:style/Theme.Translucent". Save the file and build your project again, the grey screen should desapear.

I did try this solution and it is working fine as well but it creates a new problem when we open the keyboard, I can see the screen behind the app for few milliseconds also happens when we close the keyboard... I guess that is because the app theme is transparent (Translucent)

does this happen to you as well? @rozza-m

**Comment by rozza-m** [comment]
Sorry for the delay in replying. I hadn't noticed, but yes it does exhibit this issue.

**Comment by spinninghamster** [comment]
> > For others who experience the same thing - [this](https://stackoverflow.com/questions/30994342/customizing-the-blank-screen-before-splash-screen-and-videos-not-playing-in-full) was the solution for me:
> > > In the "platforms\android" folder under your project [platforms\android\app\src\main], open the AndroidManifest.xml and search for android:theme inside the  tag that contains android:name="MainActivity" and change the default value (that is android:theme="@android:style/Theme.DeviceDefault.NoActionBar") to android:theme="@android:style/Theme.Translucent". Save the file and build your project again, the grey screen should desapear.
> 
> I did try this solution and it is working fine as well but it creates a new problem when we open the keyboard, I can see the screen behind the app for few milliseconds also happens when we close the keyboard... I guess that is because the app theme is transparent (Translucent)
> 
> does this happen to you as well? @rozza-m

I can confirm that this happens to me, too. Pretty ugly.

**Comment by BroadBrander** [comment]
:+1:  This really needs to be fixed.
