### ISSUE TITLE
Release current master as 5.0.3

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-splashscreen#199]
Current `master` should be released as 5.0.3 as preparation for merging existing Pull Requests.

**Comment by timbru31** [comment]
So far one bug is fixed it seems: https://github.com/apache/cordova-plugin-splashscreen/compare/5.0.2...master

---
However, I'd also would volunteer to make a new release together, since I'm not *that* experienced with the release process yet :)

**Comment by janpio** [comment]
Yes, the others seem to be just chore stuff so we should be good here.

Besides the suboptimal formatting https://github.com/apache/cordova-plugin-splashscreen/commit/f9c88b8ab8280df920dc0de8e101a3abe599a353 looks fine, right?

**Comment by timbru31** [comment]
IMO yes.

**Comment by janpio** [comment]
Current blocking seems to "only" be the local iOS run on CI. I hope this will get fixed via another update to Paramedic (see https://github.com/apache/cordova-paramedic/pull/131).

**Comment by janpio** [comment]
Some more CI changes:
https://github.com/apache/cordova-paramedic/pull/137
https://github.com/apache/cordova-plugin-splashscreen/pull/209

**Comment by janpio** [comment]
And ready for release with last changes merged.

**Comment by timbru31** [comment]
Go go go 🚀

**Comment by janpio** [comment]
Release was all good - then SauceLabs removed the iOS 10 simulatos so the release commits failed on CI. Starting new as soon as Travis CI confirmed that the removal of iOS simulator makes CI green again.

**Comment by janpio** [comment]
Release is done, vote email is sent.

**Comment by piotr-cz** [comment]
The 5.0.3 is not released on [npm](https://www.npmjs.com/package/cordova-plugin-splashscreen) (also no rel/5.0.3 tag)

**Comment by janpio** [comment]
Yes, because nobody voted, so I can't continue with the release process.

**Comment by sithwarrior** [comment]
@janpio this is fixed now? just checked npm and it says 5.0.3 https://www.npmjs.com/package/cordova-plugin-splashscreen

**Comment by janpio** [comment]
Yes, this was released this week.
