### ISSUE TITLE
Implement `ShowSplashScreen` for all platforms

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-splashscreen#201]
[Per the documentation](https://github.com/apache/cordova-plugin-splashscreen#browser-quirks) `ShowSplashScreen` is only implemented for Windows. Either this is a documentation problem, which then should be fixed, or it should be implemented for all platforms.

**Comment by breautek** [comment]
The plugin now only supports the browser and windows platform, so the current documentation is accurate.

For iOS & Android, splashscreen is implemented as a core feature and doesn't require the plugin. The documentation for this can be found at https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/index.html
