### ISSUE TITLE
Better Android support

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-splashscreen#202]
There are frequent reports of a white or grey screen before the splash is shown on Android. It is unclear if those are about a real problem, but if they are, it might be possible to implement a fix: https://android.jlelse.eu/right-way-to-create-splash-screen-on-android-e7f1709ba154 https://android.jlelse.eu/the-complete-android-splash-screen-guide-c7db82bce565 https://medium.com/viithiisys/android-perfect-way-to-create-splash-screen-ca3c5bee137f

TODO:
- Investigate reports
- Look at what currently is done on Android
- Look at suggested solutions from links above
- If useful, implement

**Comment by Thul999** [comment]
Is there any news on this issue?

**Comment by rozza-m** [comment]
e.g.
https://github.com/apache/cordova-plugin-splashscreen/issues/197

https://stackoverflow.com/questions/30994342/customizing-the-blank-screen-before-splash-screen-and-videos-not-playing-in-full

[this was  the solution for me](https://github.com/apache/cordova-plugin-splashscreen/issues/197#issuecomment-626785103)

**Comment by msd117** [comment]
> e.g.
> #197
> 
> https://stackoverflow.com/questions/30994342/customizing-the-blank-screen-before-splash-screen-and-videos-not-playing-in-full
> 
> [this was the solution for me](https://github.com/apache/cordova-plugin-splashscreen/issues/197#issuecomment-626785103)

That is not working for me
