### ISSUE TITLE
Documentation: Differentiation to native splash

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-splashscreen#203]
In #198 I tried to diff this plugin from the "real" native loading screens, using this paragraph:

> Note that this plugin is not about native loading screens, like e.g. ["Launch Screens" of iOS](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/). This plugin's splash screens are shown _after_ the native app has already started.

That was not really clear enough, which is why I removed it before merging.

We might still want to have something like this in the docs though, so we should think on ways to better describe this.

**Comment by breautek** [comment]
I don't think this is relevant anymore.

Android splashscreens now uses the real android splashscreens available in modern Android devices. In older android devices, it uses a compatibility library provided by Android to simulate/patch in support for real splash screens.

For iOS, it uses storyboards, which is also a real splashscreen.

Both of which can be shown before the application code starts.
