### ISSUE TITLE
Documentation: Order of legacy splash screen images and storyboard images for iOS in README

### ISSUE THREAD

**Issue by timbru31** [apache/cordova-plugin-splashscreen#205]
Personally I'd move the Storyboard method before the legacy method in order to encourage users to use this method instead.

_Originally posted by @timbru31 in https://github.com/apache/cordova-plugin-splashscreen/pull/198/files#r281043477_

**Comment by breautek** [comment]
Closing because the legacy splash screen documentatino has been completely removed.
