### ISSUE TITLE
SplashForceFullScreen

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-splashscreen#207]
There was a PR https://github.com/apache/cordova-plugin-splashscreen/pull/45:

> This change adds settings to hide the navigation and status bars while the splash screen is displayed. Full-screen apps aren't affected.

User decided to close, although changes might be relevant. This issue will allow us to revisit.

**Comment by jcesarmobile** [comment]
The new Android 12 Splash Screen API used by cordova-android 11 is full screen, so this is no longer relevant
