### ISSUE TITLE
Cordova-Electron initial 404

### ISSUE THREAD

**Issue by Polm90** [apache/cordova-plugin-splashscreen#215]
I know that on Electron this plugin is not supported, but by design, electron uses the browser implementation of the plugin (if present; and this is the case).

So at the startup, on Electron we receive a 404: 

![image](https://user-images.githubusercontent.com/4883463/58269148-384ae480-7d87-11e9-91c9-7a709e58d9a2.png)

![image](https://user-images.githubusercontent.com/4883463/58269200-56b0e000-7d87-11e9-9c89-759e503ba2dd.png)

![image](https://user-images.githubusercontent.com/4883463/58269238-67615600-7d87-11e9-94d1-23781fae1314.png)

Is it possible to fix?
Thank you

**Comment by janpio** [comment]
That line 886 of `cordova.js` looks broken - that path should probably be relative.

But does this actually come from this plugin?

**Comment by Polm90** [comment]
Without the plugin there is no error (but the readConfig function is not invoked).
So maybe we should referer the bug to the cordova electron team?

**Comment by janpio** [comment]
If this code is indeed in the electron platform repository, it might be worth opening an issue there _as well_ (and crosslinking to this one). Might very well be the fault of the Splashscreen plugin, I don't know enough what is going wrong here.

**Comment by erisu** [comment]
This was fixed but not released. https://github.com/apache/cordova-electron/pull/42
