### ISSUE TITLE
LaunchImage is used despite that I use storyboard images in LaunchStoryboard

### ISSUE THREAD

**Issue by joacim-boive** [apache/cordova-plugin-splashscreen#216]
# Bug Report

## Problem
Only storyboard splash screen is configured in config.xml:
` <splash src="res/screen/ios/Default@2x~universal~anyany.png" />
        <splash src="res/screen/ios/Default@2x~universal~comany.png" />
        <splash src="res/screen/ios/Default@2x~universal~comcom.png" />
        <splash src="res/screen/ios/Default@3x~universal~anyany.png" />
        <splash src="res/screen/ios/Default@3x~universal~anycom.png" />
        <splash src="res/screen/ios/Default@3x~universal~comany.png" />`

Despite that LaunchImage is created in the Xcode project:
<img width="746" alt="Screenshot 2019-05-24 at 09 29 35" src="https://user-images.githubusercontent.com/270235/58310284-88b55700-7e06-11e9-9be1-f9cb9af882cf.png">

### What is expected to happen?

Only the splash screen from the configured storyboard should be shown.

### What does actually happen?

Both LaunchImage and LaunchStoryboard assets are generated in the Xcode project.
Since LaunchImage isn't configured it uses default Cordova splash screen briefly and then my defined storyboard splash screen.

## Information
The solution is to delete the LaunchImage from the Xcode project, but this is tedious and easy to forget as I have to redo it manually every time.

### Environment, Platform, Device
iOS all versions

### Version information
Cordova 9.0.0
cordova-plugin-splashscreen 5.0.2

## Checklist

- [X ] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by spinninghamster** [comment]
Any fix for this?

**Comment by ananbetak** [comment]
no answer for that ?

**Comment by drogerie21** [comment]
i have the same problem. Woulr really appreciate it, if the launchimage does not get created when not defined in the config!

**Comment by HansKrywaa** [comment]
+1

**Comment by irene-pc** [comment]
Hi!

I remove LaunchImage from XCode from folder images.xcassets and now I can't simulate with XCode. I am testing to fulfill Apple requests for June 2020 and I don't sure if Launchimage from images.xcassets must be deleted.

Thanks in advanced :)

**Comment by breezertwo** [comment]
+1

**Comment by landabaso** [comment]
+1

XCode triggers the warning: `warning: 'UILaunchImages' has been deprecated, use launch storyboards instead. (in target 'XXXXX' from project 'XXXXX')`

Will get the warning even after removing `Images.xcassets/LaunchImage.launchimage` folder. In fact, after removing that folder, I cannot see the default Cordova LaunchImages in XCode.

That warning is weird. In fact, I searched for the string `UILaunchImages` inside the project and could not find it.

I could not find `ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME` or `LaunchImage` either set in any configuration file.

**Comment by jcesarmobile** [comment]
the plugin has been integrated into cordova-ios 6, so no more iOS work will be done here.
And now only storyboard is used, so this is probably fixed.
Anyway, if there are still bugs on the cordova-ios 6 implementation, report them on https://github.com/apache/cordova-ios/issues
