### ISSUE TITLE
Android: Cannot omit placeholder Cordova splashscreen Images

### ISSUE THREAD

**Issue by GitToTheHub** [apache/cordova-plugin-splashscreen#222]
# Bug Report
When i remove the Plugin or disable Splashscreen via
`<preference name="SplashScreenDelay" value="0" />`
and don't add Splash images via the splash-tags, then default cordova images are copied in my Android Project after build (using Phonegap Build)

### What is expected to happen?
it should be possible to omit the default splash screens.

### Version information
Using phonegap-version cli-8.1.1

**Comment by janpio** [comment]
Does this also happen when building locally, not using Phonegap Build?

**Comment by GitToTheHub** [comment]
I cannot test it, because i've only a smartphone :/
Are the images normally not included when the plugin is not in the project?
