### ISSUE TITLE
Crashes: android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by enesien** [apache/cordova-plugin-splashscreen#223]
**Bug**

## Description
I'm receiving several crash reports from Google Play that appear to be coming from Cordova splashscreen with the following exception:
```
android.content.res.Resources$NotFoundException: 
  at android.content.res.ResourcesImpl.getValueForDensity (ResourcesImpl.java:213)
  at android.content.res.Resources.getDrawableForDensity (Resources.java:875)
  at android.content.res.Resources.getDrawable (Resources.java:818)
  at android.content.res.Resources.getDrawable (Resources.java:793)
  at org.apache.cordova.splashscreen.SplashScreen.onConfigurationChanged (SplashScreen.java:213)
  at org.apache.cordova.PluginManager.onConfigurationChanged (PluginManager.java:509)
  at org.apache.cordova.CordovaActivity.onConfigurationChanged (CordovaActivity.java:493)
  at android.app.ActivityThread.performActivityConfigurationChanged (ActivityThread.java:5182)
  at android.app.ActivityThread.performConfigurationChangedForActivity (ActivityThread.java:5050)
  at android.app.ActivityThread.performConfigurationChangedForActivity (ActivityThread.java:5028)
  at android.app.ActivityThread.handleActivityConfigurationChanged (ActivityThread.java:5372)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1855)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6797)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:772)
```
Each stack trace looks almost exactly the same.

## Information
So far the exception has only been reported from Android 8.0 and 8.1

### Environment, Platform, Device
I added the plugin via the CLI and I build for production using the CLI, as well.

### Version information
Cordova Android Engine 7.0.0
cordova-plugin-splashscreen 5.0.2

**Comment by janpio** [comment]
Can you reproduce this crash? If so, how?

**Comment by enesien** [comment]
Sadly, I cannot. It's only happening on a small number of my user's devices and not on my device or my emulator.

**Comment by facundofarias** [comment]
Hello @enesien, we are having the exact same issue.
Any idea? Were you able to reproduce it? 
Thanks

**Comment by janpio** [comment]
What Android versions are you encountering the problem @facundofarias? Really 100% identical stacktrace? What versions of Cordova, Cordova Android and the plugin are you using?

**Comment by facundofarias** [comment]
Hello @janpio, 
This is the StackTrace in our case (almost the same):

`
android.content.res.Resources.getValue Resources.java:1352
android.content.res.Resources.getDrawable Resources.java:805
android.content.res.Resources.getDrawable Resources.java:772
org.apache.cordova.splashscreen.SplashScreen.onConfigurationChanged SplashScreen.java:213
org.apache.cordova.PluginManager.onConfigurationChanged PluginManager.java:509
org.apache.cordova.CordovaActivity.onConfigurationChanged CordovaActivity.java:493
`

But we have identified the issue, and it was basically because we didn't provide the splashscreen for landscape resolutions, but only for portrait. We were able to reproduce the issue, and by adding the settings in the config.xml, the problem was gone.

Thanks a lot!
Facundo

**Comment by facundofarias** [comment]
Maybe that's also you issue @enesien ?

**Comment by janpio** [comment]
Interesting, could you maybe create a quick reproduction app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md Then we can properly fix this to at least not crash any more.

**Comment by enesien** [comment]
Yes that makes sense as I don't have a landscape splash screen configured. Can you provide a snippet of the configuration you're referring to?

**Comment by facundofarias** [comment]
@enesien It's in the main page:

```
<platform name="android">
    <!-- Landscape SplashScreen -->
    <splash src="res/screen/android/splash-land-hdpi.png" density="land-hdpi"/>
    <splash src="res/screen/android/splash-land-ldpi.png" density="land-ldpi"/>
    <splash src="res/screen/android/splash-land-mdpi.png" density="land-mdpi"/>
    <splash src="res/screen/android/splash-land-xhdpi.png" density="land-xhdpi"/>
    <splash src="res/screen/android/splash-land-xxhdpi.png" density="land-xxhdpi"/>

    <!-- Portrait SplashScreen -->
    <splash src="res/screen/android/splash-port-hdpi.png" density="port-hdpi"/>
    <splash src="res/screen/android/splash-port-ldpi.png" density="port-ldpi"/>
    <splash src="res/screen/android/splash-port-mdpi.png" density="port-mdpi"/>
    <splash src="res/screen/android/splash-port-xhdpi.png" density="port-xhdpi"/>
    <splash src="res/screen/android/splash-port-xxhdpi.png" density="port-xxhdpi"/>
</platform>
```

**Comment by enesien** [comment]
@facundofarias thanks a lot - I think you resolved the issue!

**Comment by jameszzX** [comment]
I have the same problem.

**Comment by Mapiac** [comment]
Did you get it sorted @jameszzX  ?

**Comment by jorgehclinhares** [comment]
same problme here.

**Comment by enesien** [comment]
> same problem here.

Resolve by configuring a landscape splash screen. 

I'm assuming the exception is occuring when a user launches the app while in landscape and the app has no landscape splash screen configured.

**Comment by DavidTalevski** [comment]
To stop receiving the crash report you can add the following piece of code at SplashScreen.java
```java
// add the import
import android.content.res.Resources;

// replace the function onConfigurationChanged
public void onConfigurationChanged(Configuration newConfig) {
    if (newConfig.orientation != orientation) {
        orientation = newConfig.orientation;

        // Splash drawable may change with orientation, so reload it.
        if (splashImageView != null) {
            int drawableId = getSplashId();
            if (drawableId != 0) {
                try {
                    splashImageView.setImageDrawable(cordova.getActivity().getResources().getDrawable(drawableId));
                } catch(Resources.NotFoundException e){}
            }
        }
    }
}

```
