### ISSUE TITLE
Check available preferences

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-splashscreen#227]
While reproducing some bugs, I encountered some unclarity regarding some preferences:

- Is `SplashScreenBackgroundColor` only available on Windows? It only appears in that codebase, but is also listed in the browser quirks: https://github.com/apache/cordova-plugin-splashscreen#browser-quirks
- Is `SplashScreenSpinnerColor` only available for Windows and Android? Code seems to indicate so: https://github.com/search?q=org%3Aapache+SplashScreenSpinnerColor&type=Code

In general we should probably make clearer which of the preferences only work on some platforms (table?).

**Comment by breautek** [comment]
Documentation has vastly changed, and I think the [current documation](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/index.html) covers the concerns.
