### ISSUE TITLE
Multiple targets with different launchscreen storyboards - plugin can't find the right image

### ISSUE THREAD

**Issue by rsouthgate** [apache/cordova-plugin-splashscreen#229]
# Bug Report

## Problem

The plugin is hardcoded to look for the LaunchStoryboard asset if the app is using LaunchStoryboard. But in my app I have multiple targets with different LaunchStoryboards and each renders a different LaunchStoryboard image.

### What is expected to happen?

The plugin can figure out which storyboard the target showed and use the correct image.

### What does actually happen?

It always uses the LaunchStoryboard image

## Information
I use a different info.plist for my targets. Each has a defined UILaunchStoryboardName. And in each storyboard the view loads a different LaunchStoryboard from the asset catalog. 

So there are two issues currently... in isUsingCDVLaunchScreen the condition checks the LaunchStoryboardName is CDVLaunchScreen, but in two of my targets I'm using a differently named launch screen - but I don't understand why it should bail out just because the name is changed - surely if a UILaunchStoryboardName is defined it should attempt to use it for splash screen regardless of it's name...

And second, if that is changed the code then attempts to set the image to LaunchStoryboard, but that is incorrect and doesn't match two of my LaunchStoryboards... is it possible to query the Storyboard to see what the asset it uses is called?

### Environment, Platform, Device
iOS (all devices)

### Version information
Cordova CLI 9.0.0 (Cordova lib 9.0.1)
Cordova-ios: 5.0.1
Cordova-plugin-splashscren: 5.0.3

XCode 10.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
the plugin has been integrated into cordova-ios 6, so no more iOS work will be done here.
If there are still bugs on the cordova-ios 6 implementation, report them on https://github.com/apache/cordova-ios/issues
