### ISSUE TITLE
Update link to readme.md file in npm update output

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-plugin-splashscreen#235]
please fix link to readme.md like in  cordova-plugin-file
![image](https://user-images.githubusercontent.com/2271337/66079168-d2a40b80-e563-11e9-8b75-78febd238399.png)

what I do:
```
npm-check -u -E
```

Link should be `https://github.com/apache/cordova-plugin-splashscreen#readme` instead of `https://cordova.apache.org/`

**Comment by breautek** [comment]
I assume `npm-check` is reading

https://github.com/apache/cordova-plugin-splashscreen/blob/be85a1b14e69696b6c0355c754181c8d57d0837f/package.json#L50

Would welcome a PR.

**Comment by blackwolf12333** [comment]
I made a PR :)
