### ISSUE TITLE
Splash screen not displayed when opening the app from push notification while phone is locked - Android

### ISSUE THREAD

**Issue by jasvindersingh-evon** [apache/cordova-plugin-splashscreen#241]
# Bug Report

## Problem
Splash screen is not getting displayed when opening the app from push notification while phone is locked
### What is expected to happen?
After tapping on push notification on locked phone, the app opens and it should display the splash screen

### What does actually happen?
After tapping on push notification on locked phone, the app opens and it is not displaying the splash screen rather it is displaying blank screen

### Environment, Platform, Device

Mac OS High Sierra 10.13.6
Device - Moto G (Android 8.1.0), Samsung S7(Android 8.0.0)

### Version information

Cordova 8.0
Ionic 3.20.0

Cordova plugin ls command

card.io.cordova.mobilesdk 2.1.0 "CardIO"
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.paypal.cordova.mobilesdk 3.5.0 "PayPalMobile"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-fcm-with-dependecy-updated 2.2.4 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.11 "cordova-plugin-googlemaps"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.1.2 "NativeGeocoder"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"

## Checklist

- [x] I searched for existing GitHub issues
- [  ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by front-stream** [comment]
I have the same issue

**Comment by sachinshah391** [comment]
is it fixed?
