### ISSUE TITLE
Dark/Light mode splashscreens

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-plugin-splashscreen#246]
# Feature Request

## Feature Description
Would be nice to have 2 sets of splash screens depending on the current mode (dark vs light) so they actually match with the app UI.

**Comment by timbru31** [comment]
Is this even supported on the native side (especially iOS)?

**Comment by globules-io** [comment]
Yes you can check if the current theme is dark or light and support comes with iOS13.
Android support start at 9 (API level 28).

**Comment by breautek** [comment]
For iOS, it looks like assets can be assigned to any appearance, or just light, or just dark. https://developer.apple.com/documentation/xcode/supporting_dark_mode_in_your_interface?changes=latest_minor

On Android, dark theme is actually only available on API 29, which will be the new default and officially supported in cordova-android 9 (not currently released). It looks to be configurable by using a `-night` qualifier on the drawables. This [SO](https://stackoverflow.com/a/58892660/4685664) I think makes it easier to understand what android needs compared to reading the official docs.

https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

Just providing helpful links for anybody willing to tackle this.

**Comment by HansKrywaa** [comment]
Regarding to [this](https://stackoverflow.com/a/56892137), it's very simple for iOS, you just have to set the view "Background" color to "System Background Color". This will be white in light mode and black in dark mode. 

Is this possible at the moment?

**Comment by HansKrywaa** [comment]
Just to let you know: I think this Issue can be closed now. For iOS this works since `cordova-ios6.1.0`. I just tested around with Android this works kind of out of the Box as well. Just adding **-night** on the right Place to the `density` works (Also with NightMode on my Android 9 Device).
I will create a PR to add this Info to the Readme
