### ISSUE TITLE
Show splash screen with enabled/disabled spinner

### ISSUE THREAD

**Issue by alexverbitsky** [apache/cordova-plugin-splashscreen#248]
# Feature Request

## Motivation Behind Feature

By default we have a setting to define whether spinner should be shown or not:
`<preference name="ShowSplashScreenSpinner" value="false"/>`
To comply with [MSTG-STORAGE-9 by OWASP](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06d-Testing-Data-Storage.md) I'd like to put splash screen over the app layout to hide sensitive data when application goes to a background. But it isn't logical to show splash with spinner for this case.

## Feature Description

`Splash.show()` would accept optional parameter that define spinner presence.
`show(enableSpinner?: boolean)`
Parameter "enableSpinner" would be equal to config parameter if it isn't set during the call or to default value if it isn't set even in config.

**Comment by breautek** [comment]
For android, this isn't possible natively.

Android splashscreens doesn't have an activity and we can't add our own UI elements on the screen. The Android splashscreen simply accepts a background color and a vector for an app logo. The app logo does support animations, so in theory with some creativity, one could supply an app logo with an animated spinner of some sort, but this will be out of scope of Cordova.

For iOS, I'm not knowledgeable enough to say if it is or is not possible, so I'll leave this open ended for someone else to chime in.

**Comment by jcesarmobile** [comment]
Closing since the plugin no longer has iOS nor android code
