### ISSUE TITLE
WKWebViewOnly stops Splash Screen from operating correctly

### ISSUE THREAD

**Issue by lukesnowden** [apache/cordova-plugin-splashscreen#255]
# Bug Report

## Problem

When adding `<preference name="WKWebViewOnly" value="true" />` to the `config.xml` the splash screen hangs and does not hide.

### What is expected to happen?

Work as normal

### What does actually happen?

Splash screen hangs

## Information

Adding `<preference name="WKWebViewOnly" value="true" />` due to Apples upcoming app ban for using `UIWebView`.

### Environment, Platform, Device

Any IOS mobile device

### Version information

All latest versions

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by lukesnowden** [comment]
Sorry, my mistake. Didn't realise I had to add https://github.com/apache/cordova-plugin-wkwebview-engine plugin

**Comment by golge666** [comment]
any update i was stuck there too.

**Comment by lukesnowden** [comment]
> any update i was stuck there too.

You have to add the plugin ^
