### ISSUE TITLE
Build breaks using webp splash images instead of PNG

### ISSUE THREAD

**Issue by ausias-armesto** [apache/cordova-plugin-splashscreen#257]
# Bug Report

## Problem

I have changed my config.xml to use reduced images. I have used the *.webp format  having a config.xml similar to this
```
    <platform name="android">
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.webp" />
...
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.webp" />
       ...
    </platform>
```

### What is expected to happen?
I would expect the plugin to accept the format of the image specified in the src attribute

### What does actually happen?
I guess the only format accepted is PNG and the error produced is: 
```
* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  /Users/ausias/Trabajo/Workspaces/biometric-signature/mobile-app/biometric-signature-app/platforms/android/app/src/main/res/drawable-port-mdpi/screen.png: error: failed to read PNG signature: file does not start with PNG signature.
```

## Information

I attach the *.webp format of the cordova logo image.
[sample-files.zip](https://github.com/apache/cordova-plugin-splashscreen/files/4588460/sample-files.zip)

### Command or Code

using the build command: 
```
ionic cordova build android --release
```

### Version information

```
Ionic:

   Ionic CLI                     : 5.2.3 (/Users/ausias/.nvm/versions/node/v13.6.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.2.2
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.5.3, (and 20 other plugins)

Utility:

   cordova-res : 0.8.1 (update available: 0.14.0)
   native-run  : 0.3.0 (update available: 1.0.0)

System:

   Android SDK Tools : 26.1.1 (/Users/ausias/Library/Android/sdk)
   NodeJS            : v13.6.0 (/Users/ausias/.nvm/versions/node/v13.6.0/bin/node)
   npm               : 6.13.4
   OS                : macOS High Sierra

```

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Traditionally we only supported PNG files because webp support in android is only available as of API 17. But since `cordova-android@8` minimum API support is 19, (and will be increased to I believe 21 if my memory recalls correctly...) I see no reason why we can't extend support to webp, especially since [android](https://developer.android.com/topic/performance/network-xfer#sf) appears to recommend using webp as your first choice, if possible.

I'll add the enhancement flag to this.
