### ISSUE TITLE
Docs: Dimension sizes required for Android Splash/Icon images should be documented

### ISSUE THREAD

**Issue by breautek** [apache/cordova-plugin-splashscreen#260]
# Bug Report

## Problem

The docs only mention DPI levels, but does not mention the actual resolutions that these images should be, which is confusing for users who are trying to develop these resources.

PhoneGap Docs has the [splash screen resolutions](https://github.com/phonegap/phonegap/wiki/App-Splash-Screen-Sizes#android) and [app icon resolutions](https://github.com/phonegap/phonegap/wiki/App-Icon-Sizes#android) documented. We should include this information in our docs as well.

**Comment by ugnich** [comment]
And "supplying an image that is too large might crash your app on some devices". ;)
