### ISSUE TITLE
(iOS) cordova-ios@6.0.0 - unable to click anything in the app after the splashscreen is hidden 

### ISSUE THREAD

**Issue by antikalk** [apache/cordova-plugin-splashscreen#268]
# Bug Report

## Problem
After upgrading to cordova-ios@6.0.0 I am unable to click anything in my app after the splashscreen is hidden (using navigator.splashscreen.hide()). When removing cordova-plugin-splashscreen I am able to click everything again, but the splashscreen hides to early.

### What is expected to happen?
Splash Screen should hide and the user should be able to perform click events in the app.

### What does actually happen?
Splash Screen correctly hides but the user is unable to click anything in the app. It feels like there is an invisible layer overlaying the whole app.

### Command or Code
Config: `
    <preference name="AutoHideSplashScreen" value="false"/>
`
JS: `
initApp().then(() => {
  navigator.splashscreen.hide();
});
`

### Environment, Platform, Device
Platform iOS

### Version information
cordova-ios: 6.0.0
cordova-plugin-splashscreen: 5.0.3

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by FireLizard** [comment]
same problem.

**Comment by antikalk** [comment]
This might be related to PR #263 as the current version of this plugin still provides the iOS SplashScreen code, which should already be provided with cordova-ios@^6.0.0.

**Comment by antikalk** [comment]
Anyone else tried cordova-plugin-splashscreen@5.0.4? This seems to fix the click problem for me! The problem with the early hiding of the splashscreen still exists but that is now a cordova-ios problem, as this plugin does not contain any ios related code anymore :) Therefore I am closing this issue.

**Comment by FireLizard** [comment]
Sorry but it does not solve the problem :(

```
$ npm ls cordova cordova-ios cordova-plugin-splashscreen
my-project@0.1.0 ~
├── cordova@9.0.0 
├── cordova-ios@5.1.1
└── cordova-plugin-splashscreen@5.0.4
```

**Comment by antikalk** [comment]
@FireLizard okay, that is weird... I do not experience the "unable to click anything" issue anymore (cordova@9.0.0, cordova-ios@6.0.0, cordova-plugin-splashscreen@5.0.4).

**Comment by FireLizard** [comment]
Do you need some more info about my system? I'm using an iPhone 7 with iOS 13.3.1.
What do you use and what does `cordova info` tells you?

**Comment by filsv** [comment]
Same for me:

`Plugin doesn't support this project's cordova-ios version. cordova-ios: 6.0.0, failed version requirement: <6.0.0
Skipping 'cordova-plugin-splashscreen' for ios`

@erisu or anyone else, any updates?

**Comment by erisu** [comment]
@filsv SplashScreen has been integrated into the platform core for Cordova-iOS 6+. That means this plugin is no longer needed for Cordova-iOS 6 and up.

**You will still need this plugin for other platforms** but you can ignore the message for iOS. A SplashScreen plugin major release will be coming soon which will drop iOS from this repo (`cordova-plugin-splashscreen`) and remove the warning you are seeing.

*Again, the iOS SplashScreen code was migrated to the `cordova-ios` platform repo.*

**As for the SplashScreen+Cordova-iOS 6 issues:**

We have also already merged a PR to the master branch, of the platform, that should have resolved the issues in Cordova-iOS 6.x.

Here are the reference PR and issue ticket.
PR: https://github.com/apache/cordova-ios/pull/896
Issue: https://github.com/apache/cordova-ios/issues/890

There should be a patch release coming soon, for iOS, but I can not give you the exact ETA. But it is expected and should not take long.

If you want to test the changes, try using the `cordova-ios@nightly` or the `master` branch of `cordova-ios`. It would be great if you can test to ensure that the master resolves your issue.

Please remember that using nightly or master is not for production use as it is a development version.

**Comment by filsv** [comment]
> @filsv SplashScreen has been integrated into the platform core for Cordova-iOS 6+. That means this plugin is no longer needed for Cordova-iOS 6 and up.
> 
> 
> 
> **You will still need this plugin for other platforms** but you can ignore the message for iOS. A SplashScreen plugin major release will be coming soon which will drop iOS from this repo (`cordova-plugin-splashscreen`) and remove the warning you are seeing.
> 
> 
> 
> *Again, the iOS SplashScreen code was migrated to the `cordova-ios` platform repo.*
> 
> 
> 
> **As for the SplashScreen+Cordova-iOS 6 issues:**
> 
> 
> 
> We have already merged a PR to the master branch, of the platform, that should have resolved the issues in Cordova-iOS 6.x.
> 
> 
> 
> Here are the reference PR and issue ticket.
> 
> PR: https://github.com/apache/cordova-ios/pull/896
> 
> Issue: https://github.com/apache/cordova-ios/issues/890
> 
> 
> 
> There should be a patch release coming soon, for iOS, but I can not give you the exact ETA. But it is expected and should not take long.
> 
> 
> 
> If you want to test the changes, try using the `cordova-ios@nightly` or the `master` branch of `cordova-ios`. It would be great if you can test to ensure that the master resolves your issue.
> 
> 
> 
> Please remember that using nightly or master is not for production use as it is a development version.

Got it, thanks!!!

**Comment by antikalk** [comment]
@erisu I tested again using cordova-plugin-splashscreen@5.0.4 + cordova-ios master and everything looks good for me now :)
