### ISSUE TITLE
Can I switch the splashscreen according to dark/light? (Android)

### ISSUE THREAD

**Issue by Wa-Lt** [apache/cordova-plugin-splashscreen#271]
Hi,

Can I currently use the cordova-plugin-splashscreen to switch the background color according to the Android dark/light?

Also, is there a good way to switch the splashscreen according to dark/light in cordova-plugin-splashscreen?

Looking forward to hearing from you.

**Comment by jcesarmobile** [comment]
there is an issue discussing it already
https://github.com/apache/cordova-plugin-splashscreen/issues/246
