### ISSUE TITLE
iPhone 11 Legacy Launch Screen sizes

### ISSUE THREAD

**Issue by sboudouk** [apache/cordova-plugin-splashscreen#273]
# Feature Request

## Motivation Behind Feature

We need to know what sizes are needed for legacy launch screen for iPhone 11, X, etc.

## Feature Description

Add recent models to size documentations.

**Comment by breautek** [comment]
Legacy launch screens are deprecated by apple and support of them have been removed.

You should use storyboards instead and the sizes are already documented at https://github.com/apache/cordova-plugin-splashscreen/blob/master/README.md#multi-image-launch-screen
