### ISSUE TITLE
ios Support 6.1.0

### ISSUE THREAD

**Issue by mylertitchell** [apache/cordova-plugin-splashscreen#283]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [X] Support Question

## Description

I am updating to latest version due to alot of issues with latest ios 13.5.x release. This is my only plugin that doesn't support that version

### Command or Code

cordova platform add ios@6.1.0

### Environment, Platform, Device

Doesn't support latest cordova-ios 6.1.0

### Version information

Latest Versions

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by omar-selim** [comment]
Hello @mylertitchell 
I just had the same issue but, after checking this merged PR https://github.com/apache/cordova-plugin-splashscreen/pull/261
It seems no need to have this plugin since Cordova-iOS Platform 6.x will have splash screen integrated and no longer needs the plugin.

**Comment by timbru31** [comment]
SplashScreen has been integrated into cordova-ios@6: https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html - there is no need for iOS anymore.
