### ISSUE TITLE
6.0.1-dev in master

### ISSUE THREAD

**Issue by mvanhalen** [apache/cordova-plugin-splashscreen#285]
# Bug Report

## Problem
Looks like a dev version (6.0.1-dev) was published to master 
### What is expected to happen?
Normally it works fine in ios13 when hiding the splash screen and loading.

### What does actually happen?
It had some weird black footer at the bottom and did not work as expected. I think this version is still in development

## Information

Falling back to version 5.0.4 resolves it for me. Or the previous version

### Environment, Platform, Device

iOS iPhone X and iPhone 12

### Version information

Phonegap build / cordova

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by erisu** [comment]
Please check the `cordova-iOS` repo for an existing issue or open a new one there if the issue does not exist.

Starting from `cordova-plugin-SplashScreen@6.0.0`, this plugin no longer contains or supports the iOS.

All SplashScreen logic has been moved to the Cordova-iOS repo and is in the Cordova-iOS 6.x release. 

If your using iOS 5.x or lower then upgrade to Cordova-iOS 6.1.0.
