### ISSUE TITLE
CLI 10 (iOS 6.1.0) won't build with 5.0.4

### ISSUE THREAD

**Issue by ppetree** [apache/cordova-plugin-splashscreen#287]
# Bug Report

## Problem
Latest version of the CLI with iOS build engine 6.1.0 won't build with cordova-plugin-splashscreen version 5.0.4 with an error stating it fails the version check as the plugin requires a build engine less than 6.0.0.

### What is expected to happen?
Builds with plugin.

### What does actually happen?
Excerpt from the Voltbuilder logs
```
Installing "cordova-plugin-splashscreen" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 6.1.0, failed version requirement: <6.0.0
```

## Information
```
Discovered plugin "cordova-plugin-splashscreen". Adding it to the project
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "cordova-plugin-splashscreen@5.0.4"
fetch: Installing cordova-plugin-splashscreen@5.0.4 to 
Running command: npm install cordova-plugin-splashscreen@5.0.4 --save-dev
Command finished with error code 0: npm install,cordova-plugin-splashscreen@5.0.4,--save-dev
Copying plugin "/node_modules/cordova-plugin-splashscreen" => "/plugins/cordova-plugin-splashscreen"
Calling plugman.install on plugin "/plugins/cordova-plugin-splashscreen" for platform "ios
Installing "cordova-plugin-splashscreen" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 6.1.0, failed version requirement: <6.0.0
Skipping 'cordova-plugin-splashscreen' for ios
```

### Command or Code
Build with CLI 10 and plugin version 5.0.4.

### Environment, Platform, Device
Voltbuilder (a new cloud build service that replaces PGB). It's basically a cloud CLI.

### Version information
Cordova: Cordova CLI: 10
OS: macOS Catalina 10.15.6 (19G73) (darwin 19.6.0) x64
Node: v12.18.3
npm: 6.14.7
Xcode 11.6 

## Checklist

- [X ] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by breautek** [comment]
This is intentional.

Splashscreen code have been migrated to `cordova-ios` core and is not needed for the ios platform, so it now skips the installation for the ios platform if you're running cordova-ios@6.

If you only develop or iOS, it's safe to uninstall this plugin. If you have other platforms installed, then this plugin will be installed on supported platforms.

**Comment by erisu** [comment]
Also, ontop of what @breautek said, if you still need this plugin for other platforms, you might as well upgrade the plugin to version `6.0.0`. Version `6.0.0` removed all of the `iOS` related code from this plugin repo so the warning should not appear.

**Comment by ppetree** [comment]
Thanks! I don't know how I missed version 6.0 of this plugin, I updated them all last night.
