### ISSUE TITLE
ionic3 启动后白屏

### ISSUE THREAD

**Issue by anUniqueBoy** [apache/cordova-plugin-splashscreen#288]
<preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="0" />
    <preference name="FadeSplashScreenDuration" value="750" />
    <preference name="ShowSplashScreen" value="true" />
    <preference name="SplashScreenDelay" value="30000" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="FadeSplashScreen" value="false" />
    <preference name="loadUrlTimeoutValue" value="100000" />
    <feature name="SplashScreen">
        <param name="android-package" value="org.apache.cordova.splashscreen.SplashScreen" />
    </feature>
启动页2秒就没了，然后是白屏，白屏一段时间之后才能走到app.component里面的hide方法

如何在app。component里面不写hide方法的话也会自动隐藏，说明似乎AutoHideSplashScreen没有生效

也尝试了隐藏掉启动页，也没有生效

请问，这是什么原因呢

**Comment by anUniqueBoy** [comment]
cordova: 9.0.1
打包的是ios平台 
ionic 版本 是 3
cordova-plugin-splashscreen ：5.0.2

**Comment by timbru31** [comment]
Please use English.

**Comment by anUniqueBoy** [comment]
> Please use English.
<preference name="SplashScreen" value="screen" />
<preference name="SplashScreenDelay" value="0" />
<preference name="FadeSplashScreenDuration" value="750" />
<preference name="ShowSplashScreen" value="true" />
<preference name="SplashScreenDelay" value="30000" />
<preference name="AutoHideSplashScreen" value="false" />
<preference name="SplashShowOnlyFirstTime" value="false" />
<preference name="FadeSplashScreen" value="false" />
<preference name="loadUrlTimeoutValue" value="100000" />
<feature name="SplashScreen">
    <param name="android-package" value="org.apache.cordova.splashscreen.SplashScreen" />
</feature>
The Launched page disappears in 2 seconds, and then a blank screen. After a period of white screen, the hide method in app.component can be reached.

How to hide automatically if you don’t write the hide method in app.component, it seems that AutoHideSplashScreen does not take effect

I also tried to hide the Launched page, but it didn’t work.

may I know what is the reason

cordova: 9.0.1
The package is IOS platform
ionic ： 3
cordova-plugin-splashscreen ：5.0.2

**Comment by erisu** [comment]
What version of Cordova-iOS are you using?

**Comment by anUniqueBoy** [comment]
"cordova-ios": "^5.1.1", 
After reinstalling the dependency, I don’t know how it is all right

**Comment by erisu** [comment]
> After reinstalling the dependency, I don’t know how it is all right

Does this mean it is now working?

**Comment by anUniqueBoy** [comment]
The code was exactly the same.But when we moved as like as two peas to another git, we started to screen again after the launch.
