### ISSUE TITLE
 incompatible Cordova plugins for android, skipped install

### ISSUE THREAD

**Issue by helpceo** [apache/cordova-plugin-splashscreen#289]
Found 2 incompatible Cordova plugins for android, skipped install
    cordova-plugin-ionic-webview (5.0.0)
    cordova-plugin-splashscreen (6.0.0)
version :
"cordova-plugin-splashscreen": "^6.0.0"
"@ionic-native/splash-screen": "^5.27.0"
"@capacitor/cli": "2.4.0"

note:
iOS Same question

**Comment by breautek** [comment]
Please don't delete the issue form.
