### ISSUE TITLE
incompatible Cordova plugins for android, skipped install

### ISSUE THREAD

**Issue by helpceo** [apache/cordova-plugin-splashscreen#290]
# Bug Report

## Information
incompatible Cordova plugins for android, skipped install

### Command or Code
Found 1 incompatible Cordova plugins for android, skipped install
 cordova-plugin-splashscreen (6.0.0)

### Environment, Platform, Device
Android,iOS

### Version information
"cordova-plugin-splashscreen": "^6.0.0"
"@ionic-native/splash-screen": "^5.27.0"
"@capacitor/cli": "2.4.0"

**Comment by breautek** [comment]
Please also list your platform versions:

`cordova platform list`

**Comment by breautek** [comment]
Closing due to lack of response.

If you provide the requested information I can reopen this ticket.

With the information available, my best advice is to ensure that everything is up to date.
