### ISSUE TITLE
v6 does not support IOS?

### ISSUE THREAD

**Issue by liuyao552** [apache/cordova-plugin-splashscreen#294]
Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by breautek** [comment]
Additionally this plugin intentionally does not support `cordova-ios@6` platform, because the code base for iOS was moved into the core platform. I believe the latest major will silence the message.

This plugin is still required if you use other platforms.
