### ISSUE TITLE
The image is expanded in cases of stretched screens.

### ISSUE THREAD

**Issue by Barklim** [apache/cordova-plugin-splashscreen#295]
My problem is displaying the image on non-standard smartphones.
The image is stretched due to the non-proportional aspect ratio.

There are two cases as an example:

1. Galaxy a7 2018

Diagonal 6 inches
Resolution 2220x1080

2. Galaxy A50

Diagonal 6.4 inch
Resolution 2340x1080

Can I use some plugin tools to display the image correctly, or maybe there is some alternative solution for such resolutions.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by Barklim** [comment]
What does this template look like? Why you can't just answer yes or no. If the problem has no solution and the screens are always elongated on non-standard smartphones.

**Comment by faugusztin** [comment]
The template is shown when you press the button to create a bug report using the "New issue", then "Bug Report" button.

And the solution for your situation is to use NinePatch drawables, which use special pixels on the sides of the image to mark stretchable areas of the picture. Thus you can your centered content non-stretched, and sides/edges to stretch to fill the remaining space.
https://developer.android.com/guide/topics/graphics/drawables#nine-patch
