### ISSUE TITLE
TypeError: undefined is not an object evlaluatin navigator.splashscreen.hide

### ISSUE THREAD

**Issue by ptorrent** [apache/cordova-plugin-splashscreen#297]
Hi,

navigator.splashscreen is not defined. Working well on Android.

I'm calling navigator.splashscreen.hide() on device ready.

This is how I install the plugin:
phonegap plugin add https://github.com/apache/cordova-plugin-splashscreen.git
(no error)

navigator.device, navigator.network etc... are working well

Any ideas ?

Using phonegap version 9.0.0
Testing on emulator Iphone 8
Already try phonegap platform rm ios, phonegap platform add ios 

Thanks for your help

**Comment by breautek** [comment]
You can only use plugin APIs after the `deviceready` event has fired.

See the [docs](https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready) for more info.

**Comment by ptorrent** [comment]
yes I'm waiting devicerady... but not working

**Comment by breautek** [comment]
Please try using the cordova cli instead of the phonegap cli. Phonegap is no longer maintained.

If you still have issues, please create an issue with the entire issue form filled out.
