### ISSUE TITLE
Why is there no IOS platform

### ISSUE THREAD

**Issue by GenZhangQ** [apache/cordova-plugin-splashscreen#299]
Why is there no IOS platform in SRC file

**Comment by faugusztin** [comment]
For the reasons see #263 .

**Comment by breautek** [comment]
Splashscreen code for iOS has been moved to the core package. See the [release notes](https://cordova.apache.org/news/2020/07/21/splashscreen-plugin-release.html).

If you're using `cordova-ios@5` then you must use an older version of this plugin.

If you're using `cordova-ios@6` then you should use the latest version of this plugin. If you're only developing for the iOS platform, then it's safe to remove this plugin.
