### ISSUE TITLE
 unsafe areas behind notches in the screen.

### ISSUE THREAD

**Issue by 21pg** [apache/cordova-plugin-splashscreen#305]
# Bug Report
for iPhone XR devices I am using meta tag: `<meta name="viewport" content="user-scalable=no, initial-scale=1, width=device-width, viewport-fit=cover">` but still after first launch i am seeing white space below to notch area. 

### Version information
Cordova 10
Cordova-ios: 6.1.1
Cordova 10

@globules-io/cordova-plugin-ios-xhr 1.1.0 "Cordova WKWebView File XHR Plugin"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
-->

<preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />

![IMG_20201212_140731](https://user-images.githubusercontent.com/64975861/101980019-280b9a80-3c88-11eb-82b0-82f07dd82b8c.jpg)

## Checklist

- [ Y I searched for existing GitHub issues
- [ YI updated all Cordova tooling to most recent version
- [ Y I included all the necessary information above

**Comment by sagarchikane** [comment]
I had tried setting content inset safe values on the HTML body attribute too but that did not work out. So I did some changes within the native WKWebview implementation under `(void)updateSettings:(NSDictionary*)settings` method for the `CDVWebViewEngine.m` file under Cordova library. Following is the batch of code which was added 
```
WKWebView* wkWebView = (WKWebView*)_engineWebView; // already present as part of library code
wkWebView.scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever; // this was added
```

This makes sure that the WKContentView takes up complete screen size

**Comment by timbru31** [comment]
Actually, vice versa as the splashscreen plugin has been integrated for iOS
