### ISSUE TITLE
Splash screen is not hiding with this.splashscreen.hide() after migrated to cordova-ios >=6

### ISSUE THREAD

**Issue by SivasubramanianG** [apache/cordova-plugin-splashscreen#307]
# Bug Report

## Problem
This issue is started to occur after migrated to cordova-ios 6.0.0
### What is expected to happen?
Splash screen automatically hides with no white screen after giving this.splashscreen.hide(); in device ready function.

### What does actually happen?
Splash screen is not manually hiding even after calling this.splashscreen.hide() in device ready function.
Splash screen is not hiding without AutoHideSplashScreen set to true.
If AutoHideSplashScreen is set to true in config.xml it does not hiding with this.splashscreen.hide(). It is hiding only when setting SplashScreenDelay" value="3000" in config.xml.

## Information

Migrate cordova-ios ~5 to 6.0.0.
Upgrade splash screen to 6.0.0 version.

### Command or Code

      <preference name="SplashMaintainAspectRatio" value="true" />
     <preference name="FadeSplashScreenDuration" value="300" />
     <preference name="SplashShowOnlyFirstTime" value="false" />
     <preference name="ShowSplashScreenSpinner" value="false" />
     <preference name="SplashScreen" value="screen" />
     <preference name="AutoHideSplashScreen" value="false" />
    <platform name="android">
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
         <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
         <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
         <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
         <splash height="1125" src="resources/ios/splash/Default-Landscape-2436h.png" width="2436" />
         <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
         <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
         <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
         <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
         <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
         <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
         <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
         <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
         <splash height="2436" src="resources/ios/splash/Default-2436h.png" width="1125" />
         <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
         <splash height="1334" src="resources/ios/splash/Default@2x~iphone~anyany.jpg" width="1334" />
         <splash height="2688" src="resources/ios/splash/Default-2688h~iphone.png" width="1242" />
         <splash height="1242" src="resources/ios/splash/Default-Landscape-2688h~iphone.png" width="2688" />
         <splash height="1792" src="resources/ios/splash/Default-1792h~iphone.png" width="828" />
         <splash height="828" src="resources/ios/splash/Default-Landscape-1792h~iphone.png" width="1792" />
    </platform>

in Config.xml

this.platform.ready().then(() => {
    this.splashscreen.hide();
}

in app.component.ts

### Environment, Platform, Device

Ionic:
   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 2.3.3

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 33 other plugins)

Utility:
   cordova-res                          : not installed
   native-run (update available: 1.3.0) : 0.3.0
 
System:
   ios-deploy : 1.11.3
   ios-sim    : 8.0.2
   NodeJS     : v12.18.3 (/usr/local/bin/node)
   npm        : 6.14.6
   OS         : macOS Catalina
   Xcode      : Xcode 12.2 Build version 12B45b

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by computationalcore** [comment]
Same here. The splash screen stopped showing on Android after I upgrade to cordova-ios >=  6 and   cordova-plugin-splashscreen to 6.0.0

**Comment by SivasubramanianG** [comment]
Hi @computationalcore. 

It is working fine in Android no issues till now. I have faced this issue only in iOS >6.Fo iOS, Kindly please check this  [#1066](https://github.com/apache/cordova-ios/issues/1066). It has now fixed and updated in cordova-ios. I hope it helps for you.

Can you please share me Cordova version and Android SDK version details.

Thanks & Regards,
Sivasubramanian G

**Comment by MarcelSchuermann** [comment]
I still get a white screen after updating to cordova ios platform 6.2.0 with plugin splashscreen version 6.0.0.

It only occurs for ios platform, no problem with android.

Any ideas? Am I missing something?

**Comment by MarcelSchuermann** [comment]
Any solutions for this apart from setting AutoHideSplashScreen to true?

**Comment by MarcelSchuermann** [comment]
Somehow my ios simulator (f.e. iPhone 8 iOS 14.4) is only able to make 1 screenshot of a page then the following screenshots are the same picture like the first screenshot.
Anyone knows if this has to do with this splashscreen plugin?

**Comment by jcesarmobile** [comment]
for those using ionic-native, it's an ionic-natieve issue, reported here https://github.com/ionic-team/ionic-native/issues/3472
if not using ionic-native, then it's a cordova-ios issue, this plugin no longer includes any iOS code, it was integrated into cordova-ios, if you have problems report them in cordova-ios repository

**Comment by adamdport** [comment]
`AutoHideSplashScreen` works for me too, but it's not ideal. It relies on a set delay. On fast devices, users will have to wait longer than they need to, and on slow devices, the splash screen may hide before the app has loaded. It looks like there was already a story created under cordova-ios, but it's been closed recently as it appears to be working for at least one person under cordova-ios@6.2.0. It's **not** working for me, however, and if you're having issues I'd encourage you to head over there and make some noise: https://github.com/apache/cordova-ios/issues/1066
