### ISSUE TITLE
Overlap with the new Android 12 SplashScreen API

### ISSUE THREAD

**Issue by ollm** [apache/cordova-plugin-splashscreen#311]
# Bug Report

In Android 12 now there are two splash screens, first from the SplashScreen API and then from the plugin.

https://developer.android.com/about/versions/12/features/splash-screen
https://developer.android.com/reference/android/window/SplashScreen

### What is expected to happen?

In Android 12 it should show only the splash screen from SplashScreen API.

### What does actually happen?
Now there are two splash screens, first from the SplashScreen API and then from the plugin

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by alanmilinovic** [comment]
Any news?

**Comment by terreng** [comment]
Hi there. I added dark mode support for splash screens. This issue is on my to-do list, and I will look into it when I get the chance (no timeline, hopefully this year) if no one else has fixed it by then.

**Comment by bhandaribhumin** [comment]
@terreng  if you need any help let me know, I'll help you on this.

**Comment by hoatran2205** [comment]
Hi there. I have an issue on Android 12 that SplashScreen didn't close when app init.
My app can run with Android under 12. I used cordova-plugin-splashscreen but with android 12 it show error like:
`Msg: Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.`  
How can I solve this problem. Please help me

**Comment by terreng** [comment]
@hoatran2205 Hi there. It looks like you're using Ionic / Capacitor, [which is not compatible](https://capacitorjs.com/docs/v2/cordova/known-incompatible-plugins) with this plugin. Please let me know if I am mistaken.

**Comment by terreng** [comment]
@hoatran2205 If you are using Ionic / Capacitor, then you should be using the [Capacitor splashscreen API](https://capacitorjs.com/docs/apis/splash-screen). It sounds like the issue you are experiencing is related to Ionic / Capacitor, so I suggest you seek help elsewhere.

**Comment by jondspa** [comment]
Hi -

  Any update on a new plugin version to deal with the new Android 12 splashscreen.  I am getting an Android 12 extra splashscreen with my logo on a black background.  I've changed to use android-targetSdkVersion 31 and now I just get the black background, no logo.  I am hoping the next version of this plugin allows me to control this Android 12 splashscreen.  I've tried all ideas suggested in this thread and none work.  Maybe I can specify my own splashscreen or at least a white background.  I also upgraded to the latest version of this plugin but didn't help.  (I'm using Cordova 10.0.0 and android 9.0.0.  Thanks so much!  - Jon

**Comment by terreng** [comment]
Hi @jondspa. I added dark mode support for splash screens, and this Android 12 issue is on my to do list. I am hoping to create a fix for this issue in the next few months.

**Comment by erisu** [comment]
@terreng There is already a vote in progress for the release of **6.0.2**.

Version **6.0.2** has updated the engine requirements to `>=3.6.0 <11.0.0`. This plugin starting from 6.0.2 will not install for Cordova-Android 11.x. Obviously, if a user runs an older version of the plugin, it will install. Older versions that were released cant be changed, and usually patch releases for older major versions aren't performed.

PR that updated the engine requirements: https://github.com/apache/cordova-plugin-splashscreen/pull/329

Also a note was added to the README.

There will be a major release, 7.0.0, that will remove all of the Android source code and documentation from this repo.

Documentation for settings that remain and the addition of the new Android 12 SplashScreen API is added to the cordova-doc repo and can be seen [here](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/index.html).

**Comment by xinfengmich** [comment]
Any res/screen/android/splashscreen.xml sample per https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/index.html
