### ISSUE TITLE
cordova plugin splash sceen not working in android11 for cordova  

### ISSUE THREAD

**Issue by limrahsoft** [apache/cordova-plugin-splashscreen#335]
can you please suggest that , how to implement splash screen for cordova app on android 11 for api 30 , 31 ,32

i need cordova implementation for splash screen , not anroid coding , as we only work with cordova hybrid apps

**Comment by breautek** [comment]
Android's new splashscreen have support in cordova-android@11. When updating to cordova-android@11, this `cordova-plugin-splashscreen` plugin is no longer compatible is now obsolete. It can be uninstalled unless if you also develop for the `windows` platform. If you do develop for the windows platform, then you should update this plugin to version `6.0.2` which prevents the android code from being installed when using cordova-android@11.

Splashscreen is a breaking change. Android's splashscreen system is not 100% compatible to what Cordova had before. Documentation for the new splashscreen can be found in the [Core Documentation](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/index.html) which includes some examples, as well as a list of preferences. This documentation should be a good starting point.

We primarily use GitHub for tracking issues, so if you require further support, asking our [Slack Community](https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q) might be the best way to gain support. Alternatively you can also ask on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova).

If you think you've found a bug with cordova-android@11 relating to splashscreens, then please report it with the issue form filled out on the [cordova-android](https://github.com/apache/cordova-android/issues) repository.

**Comment by Lyfei** [comment]
> splashscreen

So how do I configure splashscreen when I use cordova-android@11. Using only icon will look deformed
