### ISSUE TITLE
Support Cordova-Android 12.0.0 (current version)

### ISSUE THREAD

**Issue by Pigsnuck** [apache/cordova-plugin-splashscreen#344]
This plugin currently doesn't support the latest version of Cordova-Android (12.0.0). How difficult would it be to support this?

**Comment by erisu** [comment]
This plugin is deprecated for the Cordova-Android. SplashScreen has been integrated into the core of the platform for quite some time now.

**Comment by breautek** [comment]
Just going to add that https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/index.html should be referenced for documentation as the docs in this repo will be out-dated.

Use this docs found in this repository if you're using the browser platform. For iOS and Android, use the aforementioned link.
